In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
RAW_DATA_PATH = Path("../data/raw/customerIQ_customer_churn_dataset.csv")
PROCESSED_DATA_PATH = Path("../data/processed/customerIQ_customer_churn_cleaned.csv")

print("Raw data path:", RAW_DATA_PATH)
print("Processed data path:", PROCESSED_DATA_PATH)

Raw data path: ..\data\raw\customerIQ_customer_churn_dataset.csv
Processed data path: ..\data\processed\customerIQ_customer_churn_cleaned.csv

In [3]:
df = pd.read_csv(RAW_DATA_PATH)

print("Dataset loaded successfully.")
print("Dataset shape:", df.shape)

Dataset loaded successfully.
Dataset shape: (10050, 15)

In [4]:
df.head()

,customer_id,age,gender,location,tenure_months,monthly_spend,total_spend,login_frequency,support_tickets,product_usage,subscription_type,payment_method,discount_used,churn,customer_lifetime_value
0,C100000,56.0,Female,Mumbai,40,1008.23,43296.89,20.0,1,68.0,Monthly,Debit Card,1,0,45804.53
1,C100001,69.0,Male,Delhi,31,1716.53,52968.01,20.0,3,87.0,Monthly,UPI,0,0,92328.73
2,C100002,46.0,Female,Mumbai,65,1035.82,72203.52,23.0,7,88.0,Monthly,Wallet,1,0,83848.62
3,C100003,32.0,Male,Other,39,2622.21,107971.82,13.0,1,68.0,Annual,UPI,0,0,126076.33
4,C100004,60.0,Male,Pune,24,2117.73,49767.32,4.0,2,80.0,Monthly,Debit Card,1,0,72619.73

In [5]:
print(df.columns.tolist())

['customer_id', 'age', 'gender', 'location', 'tenure_months', 'monthly_spend', 'total_spend', 'login_frequency', 'support_tickets', 'product_usage', 'subscription_type', 'payment_method', 'discount_used', 'churn', 'customer_lifetime_value']

In [6]:
expected_columns = [
    "customer_id",
    "age",
    "gender",
    "location",
    "tenure_months",
    "monthly_spend",
    "total_spend",
    "login_frequency",
    "support_tickets",
    "product_usage",
    "subscription_type",
    "payment_method",
    "discount_used",
    "churn",
    "customer_lifetime_value"
]

missing_columns = set(expected_columns) - set(df.columns)
extra_columns = set(df.columns) - set(expected_columns)

print("Missing expected columns:", missing_columns)
print("Unexpected columns:", extra_columns)

Missing expected columns: set()
Unexpected columns: set()

In [7]:
print(df.dtypes)

customer_id                    str
age                        float64
gender                         str
location                       str
tenure_months                int64
monthly_spend              float64
total_spend                float64
login_frequency            float64
support_tickets              int64
product_usage              float64
subscription_type              str
payment_method                 str
discount_used                int64
churn                        int64
customer_lifetime_value    float64
dtype: object

In [8]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

Missing values in each column:
customer_id                  0
age                        101
gender                       0
location                     0
tenure_months                0
monthly_spend              100
total_spend                  0
login_frequency            100
support_tickets              0
product_usage              101
subscription_type            0
payment_method               0
discount_used                0
churn                        0
customer_lifetime_value      0
dtype: int64

In [9]:
duplicate_rows = df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

Duplicate rows: 50

In [10]:
duplicate_customer_ids = df["customer_id"].duplicated().sum()

print("Duplicate customer IDs:", duplicate_customer_ids)

Duplicate customer IDs: 50

In [11]:
duplicate_customer_records = df[
    df["customer_id"].duplicated(keep=False)
]

print(duplicate_customer_records)

      customer_id   age  gender   location  tenure_months  monthly_spend  \
35        C100035  45.0    Male  Hyderabad             50        1194.15
39        C100039  68.0  Female     Mumbai             16        2510.55
251       C100251  34.0  Female       Pune             60        1511.24
321       C100321  25.0    Male  Bengaluru             35        2021.49
439       C100439  62.0  Female     Mumbai             40        2548.69
...           ...   ...     ...        ...            ...            ...
10045     C100039  68.0  Female     Mumbai             16        2510.55
10046     C104819  67.0    Male    Kolkata             59        2278.15
10047     C103465  29.0    Male      Delhi             17        2500.57
10048     C101760  32.0  Female     Mumbai             50        2502.16
10049     C102304  45.0  Female    Kolkata             23         881.53

       total_spend  login_frequency  support_tickets  product_usage  \
35        60554.58             17.0                3           47.0
39        39614.07             16.0                3           86.0
251       91185.20             12.0                3           59.0
321       73117.44             18.0                3           60.0
439      106222.82             18.0                2           86.0
...            ...              ...              ...            ...
10045     39614.07             16.0                3           86.0
10046    125295.09             13.0                1           75.0
10047     40452.28             15.0                3           75.0
10048    112085.70             15.0                1           56.0
10049     22336.84             13.0                3           93.0

      subscription_type payment_method  discount_used  churn  \
35              Monthly  Bank Transfer              1      0
39               Annual     Debit Card              1      0
251             Monthly    Credit Card              0      0
321           Quarterly    Credit Card              0      0
439           Quarterly            UPI              1      0
...                 ...            ...            ...    ...
10045            Annual     Debit Card              1      0
10046           Monthly     Debit Card              0      0
10047            Annual    Credit Card              0      0
10048            Annual            UPI              1      0
10049            Annual  Bank Transfer              1      0

       customer_lifetime_value
35                    63934.92
39                    76714.36
251                  112230.18
321                  102583.00
439                  131233.67
...                        ...
10045                 76714.36
10046                144199.55
10047                 82411.53
10048                133335.51
10049                 42231.52

[100 rows x 15 columns]

In [12]:
numeric_columns = [
    "age",
    "tenure_months",
    "monthly_spend",
    "total_spend",
    "login_frequency",
    "support_tickets",
    "product_usage",
    "churn",
    "customer_lifetime_value"
]

df[numeric_columns].describe()

,age,tenure_months,monthly_spend,total_spend,login_frequency,support_tickets,product_usage,churn,customer_lifetime_value
count,9949.000000,10050.000000,9950.000000,10050.000000,9950.000000,10050.000000,9949.000000,10050.000000,10050.000000
mean,44.039602,36.530746,1864.987437,67948.348856,14.859598,2.257811,71.107347,0.025572,92778.231514
std,15.208438,20.861434,648.250335,47517.647781,6.867592,1.516585,20.281982,0.157863,40766.519063
min,18.000000,1.000000,399.000000,430.110000,1.000000,0.000000,5.000000,0.000000,4362.610000
25%,31.000000,18.000000,1419.010000,28142.885000,10.000000,1.000000,57.000000,0.000000,61183.305000
50%,44.000000,37.000000,1859.945000,60490.415000,15.000000,2.000000,72.000000,0.000000,86848.120000
75%,57.000000,55.000000,2305.967500,99308.892500,20.000000,3.000000,87.000000,0.000000,119281.102500
max,70.000000,72.000000,4263.380000,293223.600000,35.000000,10.000000,100.000000,1.000000,272953.830000

In [13]:
negative_values = (df[numeric_columns] < 0).sum()

print("Negative values:")
print(negative_values)

Negative values:
age                        0
tenure_months              0
monthly_spend              0
total_spend                0
login_frequency            0
support_tickets            0
product_usage              0
churn                      0
customer_lifetime_value    0
dtype: int64

In [14]:
rows_before = len(df)

df = df.drop_duplicates()

rows_after = len(df)

print("Rows before:", rows_before)
print("Rows after:", rows_after)
print("Rows removed:", rows_before - rows_after)

Rows before: 10050
Rows after: 10000
Rows removed: 50

In [15]:
missing_after_cleaning = df.isnull().sum()

print("Missing values after duplicate removal:")
print(missing_after_cleaning)

Missing values after duplicate removal:
customer_id                  0
age                        100
gender                       0
location                     0
tenure_months                0
monthly_spend              100
total_spend                  0
login_frequency            100
support_tickets              0
product_usage              100
subscription_type            0
payment_method               0
discount_used                0
churn                        0
customer_lifetime_value      0
dtype: int64

In [19]:
categorical_columns = [
    "gender",
    "location",
    "subscription_type",
    "payment_method"
]

for column in categorical_columns:
    df[column] = df[column].astype("string").str.strip()

In [20]:
print(df["discount_used"].value_counts(dropna=False))

discount_used
0    6273
1    3727
Name: count, dtype: int64

In [21]:
print("Final dataset shape:", df.shape)

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

Final dataset shape: (10000, 15)

Data types:
customer_id                    str
age                        float64
gender                      string
location                    string
tenure_months                int64
monthly_spend              float64
total_spend                float64
login_frequency            float64
support_tickets              int64
product_usage              float64
subscription_type           string
payment_method              string
discount_used                int64
churn                        int64
customer_lifetime_value    float64
dtype: object

Missing values:
customer_id                  0
age                        100
gender                       0
location                     0
tenure_months                0
monthly_spend              100
total_spend                  0
login_frequency            100
support_tickets              0
product_usage              100
subscription_type            0
payment_method               0
discount_used                0
churn                        0
customer_lifetime_value      0
dtype: int64

In [22]:
PROCESSED_DATA_PATH.parent.mkdir(
    parents=True,
    exist_ok=True
)

print("Processed folder is ready.")

Processed folder is ready.

In [23]:
df.to_csv(
    PROCESSED_DATA_PATH,
    index=False
)

print(
    f"Cleaned dataset saved to: "
    f"{PROCESSED_DATA_PATH}"
)

Cleaned dataset saved to: ..\data\processed\customerIQ_customer_churn_cleaned.csv

In [24]:
cleaned_df = pd.read_csv(PROCESSED_DATA_PATH)

print("Processed dataset loaded successfully.")
print("Shape:", cleaned_df.shape)

cleaned_df.head()

Processed dataset loaded successfully.
Shape: (10000, 15)

,customer_id,age,gender,location,tenure_months,monthly_spend,total_spend,login_frequency,support_tickets,product_usage,subscription_type,payment_method,discount_used,churn,customer_lifetime_value
0,C100000,56.0,Female,Mumbai,40,1008.23,43296.89,20.0,1,68.0,Monthly,Debit Card,1,0,45804.53
1,C100001,69.0,Male,Delhi,31,1716.53,52968.01,20.0,3,87.0,Monthly,UPI,0,0,92328.73
2,C100002,46.0,Female,Mumbai,65,1035.82,72203.52,23.0,7,88.0,Monthly,Wallet,1,0,83848.62
3,C100003,32.0,Male,Other,39,2622.21,107971.82,13.0,1,68.0,Annual,UPI,0,0,126076.33
4,C100004,60.0,Male,Pune,24,2117.73,49767.32,4.0,2,80.0,Monthly,Debit Card,1,0,72619.73

In [25]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values[missing_values > 0])

Missing values in each column:
age                100
monthly_spend      100
login_frequency    100
product_usage      100
dtype: int64

In [26]:
numeric_missing_columns = [
    "age",
    "monthly_spend",
    "login_frequency",
    "product_usage"
]

print("Median values:")
print(df[numeric_missing_columns].median())

Median values:
age                  44.000
monthly_spend      1858.615
login_frequency      15.000
product_usage        72.000
dtype: float64

In [27]:
for column in numeric_missing_columns:
    df[column] = df[column].fillna(df[column].median())

print("Missing numerical values have been filled.")

Missing numerical values have been filled.

In [28]:
remaining_missing_values = df.isnull().sum()

print("Remaining missing values:")
print(remaining_missing_values[remaining_missing_values > 0])

Remaining missing values:
Series([], dtype: int64)

In [29]:
total_missing_values = df.isnull().sum().sum()

print("Total missing values:", total_missing_values)

Total missing values: 0

In [30]:
duplicate_rows_after_cleaning = df.duplicated().sum()

print("Duplicate rows after cleaning:", duplicate_rows_after_cleaning)

Duplicate rows after cleaning: 0

In [31]:
duplicate_customer_ids_after_cleaning = df["customer_id"].duplicated().sum()

print(
    "Duplicate customer IDs after cleaning:",
    duplicate_customer_ids_after_cleaning
)

Duplicate customer IDs after cleaning: 0

In [32]:
negative_values_after_cleaning = (
    df[numeric_columns] < 0
).sum()

print("Negative values after cleaning:")
print(negative_values_after_cleaning)

Negative values after cleaning:
age                        0
tenure_months              0
monthly_spend              0
total_spend                0
login_frequency            0
support_tickets            0
product_usage              0
churn                      0
customer_lifetime_value    0
dtype: int64

In [33]:
print("Final cleaned dataset shape:", df.shape)

Final cleaned dataset shape: (10000, 15)

In [34]:
print("===== FINAL DATA QUALITY REPORT =====")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate customer IDs:", df["customer_id"].duplicated().sum())

===== FINAL DATA QUALITY REPORT =====
Rows: 10000
Columns: 15
Missing values: 0
Duplicate rows: 0
Duplicate customer IDs: 0

In [35]:
df.to_csv(
    PROCESSED_DATA_PATH,
    index=False
)

print(f"Updated cleaned dataset saved to: {PROCESSED_DATA_PATH}")

Updated cleaned dataset saved to: ..\data\processed\customerIQ_customer_churn_cleaned.csv

In [36]:
cleaned_df = pd.read_csv(PROCESSED_DATA_PATH)

print("Processed dataset loaded successfully.")
print("Shape:", cleaned_df.shape)
print("Missing values:", cleaned_df.isnull().sum().sum())
print("Duplicate rows:", cleaned_df.duplicated().sum())

cleaned_df.head()

Processed dataset loaded successfully.
Shape: (10000, 15)
Missing values: 0
Duplicate rows: 0

,customer_id,age,gender,location,tenure_months,monthly_spend,total_spend,login_frequency,support_tickets,product_usage,subscription_type,payment_method,discount_used,churn,customer_lifetime_value
0,C100000,56.0,Female,Mumbai,40,1008.23,43296.89,20.0,1,68.0,Monthly,Debit Card,1,0,45804.53
1,C100001,69.0,Male,Delhi,31,1716.53,52968.01,20.0,3,87.0,Monthly,UPI,0,0,92328.73
2,C100002,46.0,Female,Mumbai,65,1035.82,72203.52,23.0,7,88.0,Monthly,Wallet,1,0,83848.62
3,C100003,32.0,Male,Other,39,2622.21,107971.82,13.0,1,68.0,Annual,UPI,0,0,126076.33
4,C100004,60.0,Male,Pune,24,2117.73,49767.32,4.0,2,80.0,Monthly,Debit Card,1,0,72619.73