In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

In [2]:
PROCESSED_DATA_PATH = Path(
    "../data/processed/customerIQ_customer_churn_cleaned.csv"
)

FEATURED_DATA_PATH = Path(
    "../data/processed/customerIQ_customer_churn_features.csv"
)

print("Processed data:", PROCESSED_DATA_PATH)
print("Feature-engineered data:", FEATURED_DATA_PATH)

Processed data: ..\data\processed\customerIQ_customer_churn_cleaned.csv
Feature-engineered data: ..\data\processed\customerIQ_customer_churn_features.csv

In [3]:
df = pd.read_csv(PROCESSED_DATA_PATH)

print("Cleaned dataset loaded successfully.")
print("Shape:", df.shape)

Cleaned dataset loaded successfully.
Shape: (10000, 15)

In [4]:
df.head()

,customer_id,age,gender,location,tenure_months,monthly_spend,total_spend,login_frequency,support_tickets,product_usage,subscription_type,payment_method,discount_used,churn,customer_lifetime_value
0,C100000,56.0,Female,Mumbai,40,1008.23,43296.89,20.0,1,68.0,Monthly,Debit Card,1,0,45804.53
1,C100001,69.0,Male,Delhi,31,1716.53,52968.01,20.0,3,87.0,Monthly,UPI,0,0,92328.73
2,C100002,46.0,Female,Mumbai,65,1035.82,72203.52,23.0,7,88.0,Monthly,Wallet,1,0,83848.62
3,C100003,32.0,Male,Other,39,2622.21,107971.82,13.0,1,68.0,Annual,UPI,0,0,126076.33
4,C100004,60.0,Male,Pune,24,2117.73,49767.32,4.0,2,80.0,Monthly,Debit Card,1,0,72619.73

In [5]:
print(df.columns.tolist())

['customer_id', 'age', 'gender', 'location', 'tenure_months', 'monthly_spend', 'total_spend', 'login_frequency', 'support_tickets', 'product_usage', 'subscription_type', 'payment_method', 'discount_used', 'churn', 'customer_lifetime_value']

In [6]:
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate customer IDs:", df["customer_id"].duplicated().sum())

Missing values: 0
Duplicate rows: 0
Duplicate customer IDs: 0

In [7]:
numeric_columns = [
    "age",
    "tenure_months",
    "monthly_spend",
    "total_spend",
    "login_frequency",
    "support_tickets",
    "product_usage"
]

df[numeric_columns].describe()

,age,tenure_months,monthly_spend,total_spend,login_frequency,support_tickets,product_usage
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,44.034000,36.538900,1864.790819,67960.619818,14.863000,2.25790,71.116900
std,15.125803,20.870804,645.363559,47546.032474,6.837098,1.51836,20.182288
min,18.000000,1.000000,399.000000,430.110000,1.000000,0.00000,5.000000
25%,31.000000,18.000000,1422.862500,28147.315000,10.000000,1.00000,57.000000
50%,44.000000,37.000000,1858.615000,60477.260000,15.000000,2.00000,72.000000
75%,57.000000,55.000000,2299.967500,99312.985000,19.000000,3.00000,87.000000
max,70.000000,72.000000,4263.380000,293223.600000,35.000000,10.00000,100.000000

In [8]:
df["average_monthly_spend"] = (
    df["total_spend"] / df["tenure_months"]
)

print(
    df[
        [
            "total_spend",
            "tenure_months",
            "average_monthly_spend"
        ]
    ].head()
)

   total_spend  tenure_months  average_monthly_spend
0     43296.89             40            1082.422250
1     52968.01             31            1708.645484
2     72203.52             65            1110.823385
3    107971.82             39            2768.508205
4     49767.32             24            2073.638333

In [9]:
print(
    df["average_monthly_spend"].describe()
)

count    10000.000000
mean      1864.152735
std        665.108145
min        351.373182
25%       1405.435372
50%       1852.087683
75%       2305.373962
max       4548.355000
Name: average_monthly_spend, dtype: float64

In [10]:
print(
    "Negative average monthly spend:",
    (df["average_monthly_spend"] < 0).sum()
)

print(
    "Missing average monthly spend:",
    df["average_monthly_spend"].isnull().sum()
)

Negative average monthly spend: 0
Missing average monthly spend: 0

In [11]:
df["usage_per_month"] = (
    df["product_usage"] / df["tenure_months"]
)

print(
    df[
        [
            "product_usage",
            "tenure_months",
            "usage_per_month"
        ]
    ].head()
)

   product_usage  tenure_months  usage_per_month
0           68.0             40         1.700000
1           87.0             31         2.806452
2           88.0             65         1.353846
3           68.0             39         1.743590
4           80.0             24         3.333333

In [12]:
print(df["usage_per_month"].describe())

print(
    "Negative values:",
    (df["usage_per_month"] < 0).sum()
)

print(
    "Missing values:",
    df["usage_per_month"].isnull().sum()
)

count    10000.000000
mean         4.754993
std          9.778174
min          0.080645
25%          1.294118
50%          1.960784
75%          3.843117
max        100.000000
Name: usage_per_month, dtype: float64
Negative values: 0
Missing values: 0

In [13]:
df["support_ticket_rate"] = (
    df["support_tickets"] / df["tenure_months"]
)

print(
    df[
        [
            "support_tickets",
            "tenure_months",
            "support_ticket_rate"
        ]
    ].head()
)

   support_tickets  tenure_months  support_ticket_rate
0                1             40             0.025000
1                3             31             0.096774
2                7             65             0.107692
3                1             39             0.025641
4                2             24             0.083333

In [14]:
print(df["support_ticket_rate"].describe())

print(
    "Negative values:",
    (df["support_ticket_rate"] < 0).sum()
)

print(
    "Missing values:",
    df["support_ticket_rate"].isnull().sum()
)

count    10000.000000
mean         0.148574
std          0.357223
min          0.000000
25%          0.029412
50%          0.058824
75%          0.125000
max          8.000000
Name: support_ticket_rate, dtype: float64
Negative values: 0
Missing values: 0

In [15]:
age_bins = [0, 25, 35, 50, np.inf]

age_labels = [
    "18-25",
    "26-35",
    "36-50",
    "51+"
]

df["age_group"] = pd.cut(
    df["age"],
    bins=age_bins,
    labels=age_labels
)

print(df["age_group"].value_counts(dropna=False))

age_group
51+      3728
36-50    2945
26-35    1867
18-25    1460
Name: count, dtype: int64

In [16]:
print(df[["age", "age_group"]].head(10))

    age age_group
0  56.0       51+
1  69.0       51+
2  46.0     36-50
3  32.0     26-35
4  60.0       51+
5  25.0     18-25
6  38.0     36-50
7  56.0       51+
8  36.0     36-50
9  40.0     36-50

In [17]:
tenure_bins = [0, 6, 12, 24, np.inf]

tenure_labels = [
    "0-6 months",
    "7-12 months",
    "13-24 months",
    "25+ months"
]

df["tenure_group"] = pd.cut(
    df["tenure_months"],
    bins=tenure_bins,
    labels=tenure_labels
)

print(
    df["tenure_group"].value_counts(dropna=False)
)

tenure_group
25+ months      6682
13-24 months    1611
0-6 months       860
7-12 months      847
Name: count, dtype: int64

In [18]:
print(
    df[
        [
            "tenure_months",
            "tenure_group"
        ]
    ].head(10)
)

   tenure_months  tenure_group
0             40    25+ months
1             31    25+ months
2             65    25+ months
3             39    25+ months
4             24  13-24 months
5             68    25+ months
6             23  13-24 months
7             61    25+ months
8             27    25+ months
9             16  13-24 months

In [19]:
new_features = [
    "average_monthly_spend",
    "usage_per_month",
    "support_ticket_rate",
    "age_group",
    "tenure_group"
]

print("New features:")
print(new_features)

print("\nFeature preview:")
print(df[new_features].head())

New features:
['average_monthly_spend', 'usage_per_month', 'support_ticket_rate', 'age_group', 'tenure_group']

Feature preview:
   average_monthly_spend  usage_per_month  support_ticket_rate age_group  \
0            1082.422250         1.700000             0.025000       51+
1            1708.645484         2.806452             0.096774       51+
2            1110.823385         1.353846             0.107692     36-50
3            2768.508205         1.743590             0.025641     26-35
4            2073.638333         3.333333             0.083333       51+

   tenure_group
0    25+ months
1    25+ months
2    25+ months
3    25+ months
4  13-24 months

In [20]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 10000
Columns: 20

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              10000 non-null  str
 1   age                      10000 non-null  float64
 2   gender                   10000 non-null  str
 3   location                 10000 non-null  str
 4   tenure_months            10000 non-null  int64
 5   monthly_spend            10000 non-null  float64
 6   total_spend              10000 non-null  float64
 7   login_frequency          10000 non-null  float64
 8   support_tickets          10000 non-null  int64
 9   product_usage            10000 non-null  float64
 10  subscription_type        10000 non-null  str
 11  payment_method           10000 non-null  str
 12  discount_used            10000 non-null  int64
 13  churn                    10000 non-null  int64
 14  customer_lifetime_value  10000 non-null  float64
 15  average_monthly_spend    10000 non-null  float64
 16  usage_per_month          10000 non-null  float64
 17  support_ticket_rate      10000 non-null  float64
 18  age_group                10000 non-null  category
 19  tenure_group             10000 non-null  category
dtypes: category(2), float64(9), int64(4), str(5)
memory usage: 1.4 MB

In [22]:
print(
    "Total missing values:",
    df.isnull().sum().sum()
)

Total missing values: 0

In [23]:
FEATURED_DATA_PATH.parent.mkdir(
    parents=True,
    exist_ok=True
)

df.to_csv(
    FEATURED_DATA_PATH,
    index=False
)

print(
    f"Feature-engineered dataset saved to: "
    f"{FEATURED_DATA_PATH}"
)

Feature-engineered dataset saved to: ..\data\processed\customerIQ_customer_churn_features.csv

In [24]:
featured_df = pd.read_csv(
    FEATURED_DATA_PATH
)

print(
    "Feature-engineered dataset loaded successfully."
)

print(
    "Shape:",
    featured_df.shape
)

print(
    "Missing values:",
    featured_df.isnull().sum().sum()
)

Feature-engineered dataset loaded successfully.
Shape: (10000, 20)
Missing values: 0

In [25]:
print(
    featured_df[
        [
            "average_monthly_spend",
            "usage_per_month",
            "support_ticket_rate",
            "age_group",
            "tenure_group"
        ]
    ].head()
)

   average_monthly_spend  usage_per_month  support_ticket_rate age_group  \
0            1082.422250         1.700000             0.025000       51+
1            1708.645484         2.806452             0.096774       51+
2            1110.823385         1.353846             0.107692     36-50
3            2768.508205         1.743590             0.025641     26-35
4            2073.638333         3.333333             0.083333       51+

   tenure_group
0    25+ months
1    25+ months
2    25+ months
3    25+ months
4  13-24 months

In [26]:
# Check the data types of all features

print(df.dtypes)

customer_id                     str
age                         float64
gender                          str
location                        str
tenure_months                 int64
monthly_spend               float64
total_spend                 float64
login_frequency             float64
support_tickets               int64
product_usage               float64
subscription_type               str
payment_method                  str
discount_used                 int64
churn                         int64
customer_lifetime_value     float64
average_monthly_spend       float64
usage_per_month             float64
support_ticket_rate         float64
age_group                  category
tenure_group               category
dtype: object

In [14]:
# Define categorical features

categorical_features = [
    "gender",
    "location",
    "subscription_type",
    "payment_method",
    "age_group",
    "tenure_group"
]

print("Categorical features:")
print(categorical_features)

Categorical features:
['gender', 'location', 'subscription_type', 'payment_method', 'age_group', 'tenure_group']

In [15]:
# Define numerical features

numerical_features = [
    "age",
    "tenure_months",
    "monthly_spend",
    "total_spend",
    "login_frequency",
    "support_tickets",
    "product_usage",
    "discount_used",
    "average_monthly_spend",
    "usage_per_month",
    "support_ticket_rate"
]

print("Numerical features:")
print(numerical_features)

Numerical features:
['age', 'tenure_months', 'monthly_spend', 'total_spend', 'login_frequency', 'support_tickets', 'product_usage', 'discount_used', 'average_monthly_spend', 'usage_per_month', 'support_ticket_rate']

In [21]:
print("Categorical columns present:")
print(set(categorical_features).issubset(df.columns))

print("\nNumerical columns present:")
print(set(numerical_features).issubset(df.columns))

Categorical columns present:
True

Numerical columns present:
True

In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

print("Preprocessing tools imported successfully.")

Preprocessing tools imported successfully.

In [23]:
numeric_transformer = StandardScaler()

categorical_transformer = OneHotEncoder(handle_unknown="ignore")

print("Numeric transformer:", numeric_transformer)
print("Categorical transformer:", categorical_transformer)

Numeric transformer: StandardScaler()
Categorical transformer: OneHotEncoder(handle_unknown='ignore')

In [24]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numerical_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

print("Preprocessor created successfully.")
print(preprocessor)

Preprocessor created successfully.
ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['age', 'tenure_months', 'monthly_spend',
                                  'total_spend', 'login_frequency',
                                  'support_tickets', 'product_usage',
                                  'discount_used', 'average_monthly_spend',
                                  'usage_per_month', 'support_ticket_rate']),
                                ('cat', OneHotEncoder(handle_unknown='ignore'),
                                 ['gender', 'location', 'subscription_type',
                                  'payment_method', 'age_group',
                                  'tenure_group'])])

In [25]:
from sklearn.pipeline import Pipeline

preprocessing_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor)
    ]
)

print("Preprocessing pipeline created successfully.")
print(preprocessing_pipeline)

Preprocessing pipeline created successfully.
Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['age', 'tenure_months',
                                                   'monthly_spend',
                                                   'total_spend',
                                                   'login_frequency',
                                                   'support_tickets',
                                                   'product_usage',
                                                   'discount_used',
                                                   'average_monthly_spend',
                                                   'usage_per_month',
                                                   'support_ticket_rate']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'location',
                                                   'subscription_type',
                                                   'payment_method',
                                                   'age_group',
                                                   'tenure_group'])]))])

In [26]:
predictor_features = numerical_features + categorical_features

print("Total predictor features:", len(predictor_features))
print(predictor_features)

Total predictor features: 17
['age', 'tenure_months', 'monthly_spend', 'total_spend', 'login_frequency', 'support_tickets', 'product_usage', 'discount_used', 'average_monthly_spend', 'usage_per_month', 'support_ticket_rate', 'gender', 'location', 'subscription_type', 'payment_method', 'age_group', 'tenure_group']

In [27]:
y_churn = df["churn"]

print("Churn target created.")
print("Shape:", y_churn.shape)
print("\nChurn value counts:")
print(y_churn.value_counts())

Churn target created.
Shape: (10000,)

Churn value counts:
churn
0    9743
1     257
Name: count, dtype: int64

In [28]:
y_clv = df["customer_lifetime_value"]

print("CLV target created.")
print("Shape:", y_clv.shape)
print("\nCLV summary:")
print(y_clv.describe())

CLV target created.
Shape: (10000,)

CLV summary:
count     10000.000000
mean      92786.741109
std       40785.688749
min        4362.610000
25%       61173.130000
50%       86848.120000
75%      119290.585000
max      272953.830000
Name: customer_lifetime_value, dtype: float64

In [29]:
X = df[predictor_features]

print("X shape:", X.shape)
print("Churn target shape:", y_churn.shape)
print("CLV target shape:", y_clv.shape)

X shape: (10000, 17)
Churn target shape: (10000,)
CLV target shape: (10000,)

In [30]:
from sklearn.model_selection import train_test_split

X_train_churn, X_test_churn, y_train_churn, y_test_churn = train_test_split(
    X,
    y_churn,
    test_size=0.2,
    random_state=42,
    stratify=y_churn
)

print("Training features:", X_train_churn.shape)
print("Testing features:", X_test_churn.shape)
print("Training target:", y_train_churn.shape)
print("Testing target:", y_test_churn.shape)

Training features: (8000, 17)
Testing features: (2000, 17)
Training target: (8000,)
Testing target: (2000,)

In [31]:
print("Training churn distribution:")
print(y_train_churn.value_counts(normalize=True))

print("\nTesting churn distribution:")
print(y_test_churn.value_counts(normalize=True))

Training churn distribution:
churn
0    0.97425
1    0.02575
Name: proportion, dtype: float64

Testing churn distribution:
churn
0    0.9745
1    0.0255
Name: proportion, dtype: float64

In [32]:
X_train_churn_processed = preprocessing_pipeline.fit_transform(X_train_churn)

print("Churn training data preprocessing completed.")
print("Processed training shape:", X_train_churn_processed.shape)

Churn training data preprocessing completed.
Processed training shape: (8000, 38)

In [33]:
X_test_churn_processed = preprocessing_pipeline.transform(X_test_churn)

print("Churn test data preprocessing completed.")
print("Processed test shape:", X_test_churn_processed.shape)

Churn test data preprocessing completed.
Processed test shape: (2000, 38)

In [34]:
print("Processed churn training shape:", X_train_churn_processed.shape)
print("Processed churn test shape:", X_test_churn_processed.shape)

print("\nProcessed data type:")
print(type(X_train_churn_processed))

Processed churn training shape: (8000, 38)
Processed churn test shape: (2000, 38)

Processed data type:
<class 'numpy.ndarray'>

In [35]:
X_train_clv, X_test_clv, y_train_clv, y_test_clv = train_test_split(
    X,
    y_clv,
    test_size=0.2,
    random_state=42
)

print("Training features:", X_train_clv.shape)
print("Testing features:", X_test_clv.shape)
print("Training target:", y_train_clv.shape)
print("Testing target:", y_test_clv.shape)

Training features: (8000, 17)
Testing features: (2000, 17)
Training target: (8000,)
Testing target: (2000,)

In [36]:
X_train_clv_processed = preprocessing_pipeline.fit_transform(X_train_clv)

print("CLV training data preprocessing completed.")
print("Processed training shape:", X_train_clv_processed.shape)

CLV training data preprocessing completed.
Processed training shape: (8000, 38)

In [37]:
X_test_clv_processed = preprocessing_pipeline.transform(X_test_clv)

print("CLV test data preprocessing completed.")
print("Processed test shape:", X_test_clv_processed.shape)

CLV test data preprocessing completed.
Processed test shape: (2000, 38)

In [38]:
print("Processed CLV training shape:", X_train_clv_processed.shape)
print("Processed CLV test shape:", X_test_clv_processed.shape)

print("\nProcessed data type:")
print(type(X_train_clv_processed))

Processed CLV training shape: (8000, 38)
Processed CLV test shape: (2000, 38)

Processed data type:
<class 'numpy.ndarray'>